# Generated by Django 4.1.2 on 2024-10-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrsapp', '0002_alter_booking_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
